Core integration
liveview-native/liveview-client-jetpack pull request #60
Opened 2023-03-30 16:29 UTC by Kashif-E

Updated client to use  Core to traverse DOM and build composable views

2023-03-31 13:40 UTC, AZholtkevych commented
@KronicDeth could you please make a code review if possible? Thank you so much in advance

2023-04-03 22:56 UTC, KronicDeth requested changes
Remove the commented out code

2023-04-03 22:56 UTC, KronicDeth commented on liveview-android/src/main/java/org/phoenixframework/liveview/data/dto/TextDTO.kt
> +
```suggestion
```

2023-04-03 22:56 UTC, KronicDeth commented on liveview-android/src/main/java/org/phoenixframework/liveview/domain/LiveViewCoordinator.kt
> +                            println("Removed: ${context.getNodeString(nodeRef)}")
This is just printing and not logging. Where does the `stdout` go when it is used on an Android device?

2023-04-03 22:56 UTC, KronicDeth commented on liveview-android/src/main/java/org/phoenixframework/liveview/domain/factory/ComposableNodeFactory.kt
>              .also { builder ->
This whole `.also` should be removed since its lambda is commented out.

2023-04-04 16:47 UTC, KronicDeth approved these changes

2023-04-04 17:10 UTC, merged